
name: gigacharge
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  mime: ^2.0.0
  mobile_scanner: ^6.0.2
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/car.png
    - assets/messages.json
    - assets/fakeData.json
    - assets/messages.json
