// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4qgimTFtacEyFCOP5urgmB7LcbyLNtvA',
    appId: '1:940594068884:web:6cf1980552e3af212e2381',
    messagingSenderId: '940594068884',
    projectId: 'giga-charga',
    authDomain: 'giga-charga.firebaseapp.com',
    storageBucket: 'giga-charga.firebasestorage.app',
    measurementId: 'G-6SHVEEGJQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD1IKMM1R4pZcZmFIbPt4cnEaiBiXbSM4',
    appId: '1:940594068884:android:60f857ed0089e43b2e2381',
    messagingSenderId: '940594068884',
    projectId: 'giga-charga',
    storageBucket: 'giga-charga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9z3PbjyXhrEXJsQU4aQqG5JpJbcfoWeQ',
    appId: '1:940594068884:ios:18751e93b9e91c5a2e2381',
    messagingSenderId: '940594068884',
    projectId: 'giga-charga',
    storageBucket: 'giga-charga.firebasestorage.app',
    iosBundleId: 'com.example.gigacharge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9z3PbjyXhrEXJsQU4aQqG5JpJbcfoWeQ',
    appId: '1:940594068884:ios:18751e93b9e91c5a2e2381',
    messagingSenderId: '940594068884',
    projectId: 'giga-charga',
    storageBucket: 'giga-charga.firebasestorage.app',
    iosBundleId: 'com.example.gigacharge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4qgimTFtacEyFCOP5urgmB7LcbyLNtvA',
    appId: '1:940594068884:web:5a8f9e5e59ae26702e2381',
    messagingSenderId: '940594068884',
    projectId: 'giga-charga',
    authDomain: 'giga-charga.firebaseapp.com',
    storageBucket: 'giga-charga.firebasestorage.app',
    measurementId: 'G-13D85VPZ16',
  );

}